import { ClueDefinition } from '../../types';

export const clues: ClueDefinition[] = [
  // ===== A 级：表层事实 =====
  {
    id: 'A1',
    tier: 'A',
    name: '配给缺口公示',
    description: '本周配给缺口被标注为“可控”，但儿童药品缺口异常偏高。',
    obtainedFrom: '入口广场公示墙',
    location: 'city_gate',
  },
  {
    id: 'A2',
    tier: 'A',
    name: '抚养资格降级通知',
    description: '系统已将余岚的临时抚养资格标记为降级观察。',
    obtainedFrom: '配给审理厅终端通知',
    location: 'ration_hall',
    setsFlags: ['guardianship_downgrade_confirmed'],
  },
  {
    id: 'A3',
    tier: 'A',
    name: '药品断档记录',
    description: '小柏的心肺药在三天前被系统自动中断，理由是“风险重分配”。',
    obtainedFrom: '社区互助站领药册',
    location: 'mutual_station',
  },

  // ===== B 级：责任与关系层 =====
  {
    id: 'B1',
    tier: 'B',
    name: '信用豁免条款',
    description: '严彻承认系统确有“临时人道豁免”条款，但默认不对外公开。',
    obtainedFrom: '严彻信任度 58+ 后说明规则边界',
    requiredTrust: { npcId: 'yanche', level: 58 },
    setsFlags: ['credit_rule_exception_known'],
  },
  {
    id: 'B2',
    tier: 'B',
    name: '生日口令卡',
    description: '卡片显示余岚为小柏准备的生日口令，证明其长期照护与依附关系。',
    obtainedFrom: '庇护区家庭抽屉',
    location: 'shelter_block',
    setsFlags: ['family_bond_confirmed'],
  },
  {
    id: 'B3',
    tier: 'B',
    name: '灰市重路由订单',
    description: '折鸦承认有“优先重路由”订单，配给流向被人为二次分配。',
    obtainedFrom: '折鸦信任度 62+ 后交代重路由细节',
    requiredTrust: { npcId: 'zheya', level: 62 },
    setsFlags: ['exposed_supply_abuse'],
  },
  {
    id: 'B4',
    tier: 'B',
    name: '七户联名申诉',
    description: '秦嫂拿出七户联名申诉，证明降级并非个例而是结构性问题。',
    obtainedFrom: '秦嫂信任度 60+ 后提交联名记录',
    requiredTrust: { npcId: 'qinsao', level: 60 },
    setsFlags: ['formed_civic_consensus'],
  },
  {
    id: 'B5',
    tier: 'B',
    name: '维护告警回执',
    description: '贺沉提供旧告警回执，显示核心补丁曾多次被紧急回滚。',
    obtainedFrom: '贺沉信任度 64+ 后提供维护告警',
    requiredTrust: { npcId: 'hechen', level: 64 },
    setsFlags: ['core_patch_warning'],
  },

  // ===== C 级：结构与隐层 =====
  {
    id: 'C1',
    tier: 'C',
    name: '配给路由缓存证据',
    description: '缓存链显示同一批配给被重复重定向，去向与公开名单不一致。',
    obtainedFrom: '灰市路由缓存盒',
    location: 'gray_market',
    requiredFlag: 'lead_supply_reroute',
    setsFlags: ['found_supply_reroute_cache'],
  },
  {
    id: 'C2',
    tier: 'C',
    name: '防线伤亡裁剪日志',
    description: '黑匣子日志显示防线伤亡明细被系统裁剪，公开版本低估了风险。',
    obtainedFrom: '防线黑匣子模块',
    location: 'defense_spire',
    requiredFlag: 'lead_breach_suppressed',
    forbiddenFlags: ['defense_detail_trimmed'],
    setsFlags: ['exposed_breach_truth'],
  },
  {
    id: 'C3',
    tier: 'C',
    name: '后门补丁签名冲突',
    description: '核心维护舱记录显示补丁签名存在冲突，后门封堵并非单纯技术事故。',
    obtainedFrom: '核心维护舱补丁日志',
    location: 'core_ring',
    requiredFlag: 'can_enter_core_ring',
    forbiddenFlags: ['core_backdoor_patched'],
    setsFlags: ['core_patch_conflict'],
  },
  {
    id: 'C4',
    tier: 'C',
    name: '抚养记录缺口镜像',
    description: '档案镜像中存在整段抚养记录缺页，时间点与降级判定高度重叠。',
    obtainedFrom: '抄录档案终端镜像库',
    location: 'data_archive',
    requiredFlag: 'lead_care_record_gap',
    forbiddenFlags: ['supply_reroute_finalized'],
    setsFlags: ['found_care_gap'],
  },
  {
    id: 'C5',
    tier: 'C',
    name: '第零层双账本',
    description: '冷库中同一事件存在两套账本：一套对公众，一套仅供中枢防线策略调用。',
    obtainedFrom: '第零层冷库主阵列',
    location: 'layer0_vault',
    requiredFlag: 'exposed_breach_truth',
    setsFlags: ['found_zero_layer_protocol', 'recognized_layer_tamper'],
  },

  // ===== X 级：干扰项 =====
  {
    id: 'X1',
    tier: 'X',
    name: '收钱降级传闻',
    description: '匿名频道断言余岚“花钱跑失败”，但无实证。',
    obtainedFrom: '入口频道流言',
    isFalse: true,
  },
  {
    id: 'X2',
    tier: 'X',
    name: '互助站内线论',
    description: '流言称阿寂与互助站勾连操盘降级。（失真叙述）',
    obtainedFrom: '互助站闲话',
    isFalse: true,
  },
  {
    id: 'X3',
    tier: 'X',
    name: '训练噪音说',
    description: '旧清单把高维告警归类为“训练噪音”，误导性很强。',
    obtainedFrom: '第零层过时清单',
    location: 'layer0_vault',
    isFalse: true,
  },
];
