import { ClueDefinition } from '../../types';

export const clues: ClueDefinition[] = [
  // ===== A 级：表层线索（证明汉克不具直接行凶条件） =====
  {
    id: 'A1',
    tier: 'A',
    name: '短刀销售记录',
    description: '账册显示凶器短刀在案发前数日已售出，购买者只记“年轻男子”。',
    obtainedFrom: '搜查铁匠铺账册',
    location: 'forge',
  },
  {
    id: 'A2',
    tier: 'A',
    name: '村医诊疗批注',
    description: '米拉的批注指出：案发后雷恩有急跑擦伤，汉克手伤则更像“拔刀救人”留下。',
    obtainedFrom: '在诊所查看病历并获得米拉解释',
    location: 'clinic',
  },
  {
    id: 'A3',
    tier: 'A',
    name: '汉克的手伤',
    description: '汉克掌部割裂方向符合“抓握拔刀”，与“握刀刺入”受力不一致。',
    obtainedFrom: '在地窖观察汉克双手，结合村医判断',
    location: 'cellar',
  },
  {
    id: 'A4',
    tier: 'A',
    name: '血迹喷溅方向',
    description: '门前残留喷溅方向与汉克被发现姿势不符，行凶位点另有其人。',
    obtainedFrom: '搜查铁匠铺门前血痕',
    location: 'forge',
  },

  // ===== B 级：核心线索（指向雷恩） =====
  {
    id: 'B1',
    tier: 'B',
    name: '赌牌事实',
    description: '费恩到村后与雷恩长期赌牌，酒馆牌桌残痕与多人口供一致。',
    obtainedFrom: '与玛莎/加雷斯交流后再查牌桌，或通过对话直接确认',
    location: 'tavern',
  },
  {
    id: 'B2',
    tier: 'B',
    name: '雷恩的威胁言论',
    description: '玛莎证实雷恩曾在赌输后摔杯放话：“我会让他好看。”',
    obtainedFrom: '玛莎信任度 70+ 时透露',
    requiredTrust: { npcId: 'martha', level: 70 },
  },
  {
    id: 'B3',
    tier: 'B',
    name: '雷恩当晚行踪',
    description: '玛莎看到雷恩案发夜从铁匠铺方向急跑，神色慌乱。',
    obtainedFrom: '玛莎信任度 70+ 时透露',
    requiredTrust: { npcId: 'martha', level: 70 },
  },
  {
    id: 'B4',
    tier: 'B',
    name: '后门泥脚印',
    description: '后门脚印鞋码与步幅均不似汉克，更接近年轻人。',
    obtainedFrom: '先通过NPC拿到脚印判断线索，再搜查铁匠铺后门',
    location: 'forge',
  },
  {
    id: 'B5',
    tier: 'B',
    name: '血衣',
    description: '雷恩房间深处藏有沾血外套，血迹分布符合近距离刺击后回溅。',
    obtainedFrom: '获准搜宅后，通过对话锁定“房间方向”再搜查雷恩房间（夜间前有效）',
    location: 'elder_house',
    requiredFlag: 'can_search_house',
    forbiddenFlags: ['blood_clothes_destroyed'],
  },
  {
    id: 'B6',
    tier: 'B',
    name: '雷恩的矛盾陈述',
    description: '雷恩自称“只见过费恩几次”，却能说出过细赌桌细节，口供前后冲突。',
    obtainedFrom: '与雷恩多轮对话，抓住矛盾后施压或出示证据',
  },
  {
    id: 'B7',
    tier: 'B',
    name: '偷窃旧账',
    description: '多名村民承认雷恩早有偷拿铁料前科，只是碍于村长面子未公开。',
    obtainedFrom: '诺拉高信任或加雷斯站位后提供',
  },
  {
    id: 'B8',
    tier: 'B',
    name: '雷恩试图逃跑',
    description: '午后山道出现雷恩背包离村行为，见到你后神色剧变。',
    obtainedFrom: '在午后时段前往村后山道触发（傍晚后失效）',
    location: 'mountain_path',
    requiredFlag: 'renn_fleeing',
  },

  // ===== C 级：深层线索（沉默成因与阴谋） =====
  {
    id: 'C1',
    tier: 'C',
    name: '汉克的秘密加班',
    description: '多方口供一致：汉克近来常半夜打铁，且刻意避开白天视线。',
    obtainedFrom: '与诺拉/加雷斯/米拉对话深入后拼合',
  },
  {
    id: 'C2',
    tier: 'C',
    name: '藏匿的武器',
    description: '铁匠铺暗格内藏有成批短剑匕首，显然并非普通农具订单。',
    obtainedFrom: '拿到“半夜打铁”调查引导并接触汉克后，搜查铁匠铺地板',
    location: 'forge',
    setsFlags: ['found_weapons'],
  },
  {
    id: 'C3',
    tier: 'C',
    name: '山道车辙',
    description: '山道窄轮车辙通向山里，说明有人持续进行夜间转运。',
    obtainedFrom: '搜查村后山道',
    location: 'mountain_path',
  },
  {
    id: 'C4',
    tier: 'C',
    name: '艾德蒙的威胁',
    description: '汉克坦白：艾德蒙以“私造武器连坐诺拉”威胁他闭口。',
    obtainedFrom: '汉克信任度 80+ 且已发现 C2',
    requiredTrust: { npcId: 'hank', level: 80 },
    requiredFlag: 'found_weapons',
  },
  {
    id: 'C5',
    tier: 'C',
    name: '密信',
    description: '书房密信显示邻领准备低价强征鸦石村铁矿，费恩是执行环节之一。',
    obtainedFrom: '进入书房并在对话引导下锁定文书后搜查',
    location: 'elder_house',
    requiredFlag: 'can_enter_study',
    setsFlags: ['found_letter'],
  },

  // ===== X 级：误导线索 =====
  {
    id: 'X1',
    tier: 'X',
    name: '汉克与费恩争吵',
    description: '艾德蒙强调两人有激烈争吵，但实为矿价谈判，不足以指向杀机。',
    obtainedFrom: '艾德蒙对话中抛出的引导信息',
    isFalse: true,
  },
  {
    id: 'X2',
    tier: 'X',
    name: '神秘外来人',
    description: '矿工口中的“陌生人”多为以讹传讹，与命案无直接关联。',
    obtainedFrom: '矿工闲聊',
    isFalse: true,
  },
  {
    id: 'X3',
    tier: 'X',
    name: '费恩债务纠纷',
    description: '费恩确有外地债务传闻，但与当夜凶案动机链条不直接重合。',
    obtainedFrom: '酒馆闲谈',
    isFalse: true,
  },
];
