import { ClueDefinition } from '../../types';

export const clues: ClueDefinition[] = [
  // ===== A 级：事实层 =====
  {
    id: 'A1',
    tier: 'A',
    name: '驿站日志涂改',
    description: '驿站日志在同一行留下两次不同笔迹的时间记号，说明延迟确实发生，而责任也先被牢牢钉在最后经手的人身上。',
    obtainedFrom: '搜查驿站柜台后的日志簿',
    location: 'relay_station',
    setsFlags: ['confirmed_lina_delay'],
  },
  {
    id: 'A2',
    tier: 'A',
    name: '半日之差',
    description: '乔安病亡时间与抚恤回执送达时间只差半日。这里杀人的不是刀，而是制度里看似正常的“晚半步”。',
    obtainedFrom: '查看港务公告栏上的讣告与收文记录',
    location: 'harbor_gate',
  },
  {
    id: 'A3',
    tier: 'A',
    name: '亲签暂存',
    description: '莉娜在回执背面留有亲签和暂存记号，说明她碰过这份回执，也说明程序最容易把罪停在“碰过的人”身上。',
    obtainedFrom: '搜查驿站暂存格',
    location: 'relay_station',
  },

  // ===== B 级：责任层 =====
  {
    id: 'B1',
    tier: 'B',
    name: '监护权风险',
    description: '在抚恤到账前，阿哲可能被债主申请临时监护，房契与抚恤都会落入“代管”。孩子在这套制度里，先被当成可重新分配的责任单位。',
    obtainedFrom: '阿哲信任度 55+ 后透露债主施压细节（需先建立监护链话题）',
    requiredTrust: { npcId: 'azhe', level: 55 },
    setsFlags: ['guardianship_risk_confirmed'],
  },
  {
    id: 'B2',
    tier: 'B',
    name: '晚送两日交易',
    description: '魏德承认有人出钱要求“晚两日再送”，并交代了代投中转人名。延迟一旦可以定价，漏洞就变成了生意。',
    obtainedFrom: '魏德信任度 68+ 后给出口供（需先打开私驿线）',
    requiredTrust: { npcId: 'weide', level: 68 },
    setsFlags: ['exposed_proxy_network'],
  },
  {
    id: 'B3',
    tier: 'B',
    name: '程序最低延迟',
    description: '马修提供书吏记录：即使流程完全合法，最早也会天然延迟一日。程序的“正常速度”，本身就在逼弱者先吃亏。',
    obtainedFrom: '马修信任度 52+ 后出示流程记录',
    requiredTrust: { npcId: 'matthew', level: 52 },
  },
  {
    id: 'B4',
    tier: 'B',
    name: '乔安口供片段',
    description: '乔安临终前留下口供：她不怪莉娜，真正逼死她的是催债链条。受害者第一次不再只是流程结果，而有了自己的版本。',
    obtainedFrom: '阿哲信任度 75+ 后交出母亲口供布条',
    requiredTrust: { npcId: 'azhe', level: 75 },
  },

  // ===== C 级：结构层 =====
  {
    id: 'C1',
    tier: 'C',
    name: '同编号双回执',
    description: '旧仓库里出现两份同编号回执，日期不同、印章一致。它说明被改写的可能不只是流程，而是流程能被公开看见的版本。',
    obtainedFrom: '拿到仓库钥匙线后搜查旧仓库铁箱',
    location: 'old_warehouse',
    requiredFlag: 'lead_warehouse_key',
    setsFlags: ['found_duplicate_receipt'],
  },
  {
    id: 'C2',
    tier: 'C',
    name: '代投暗账',
    description: '公证所账簿中记录着“代投手续费”，与回执延迟时间高度相关。不公一旦能被精确记账，它就不再是漏洞，而是业务。',
    obtainedFrom: '取得公证档案权限并锁定费码入口后搜查档案柜',
    location: 'notary_hall',
    requiredFlag: 'can_search_notary_archive',
    forbiddenFlags: ['notary_books_burned'],
    setsFlags: ['found_notary_ledger'],
  },
  {
    id: 'C3',
    tier: 'C',
    name: '私驿路线图',
    description: '码头私驿绕开官方时钟登记点，专门制造“时间差盲区”。这条线不是例外，而是灰石港能长期吃掉晚半步的毛细血管。',
    obtainedFrom: '获得私驿路线线头后搜查码头账房地板夹层',
    location: 'wharf_office',
    requiredFlag: 'lead_private_route',
    setsFlags: ['found_private_route'],
  },
  {
    id: 'C4',
    tier: 'C',
    name: '七起旧案',
    description: '旧档案显示近三年有 7 起“回执晚到后债务重组”案例，模式几乎一致。文明最可怕的，不是一次错误，而是能被归档重复的错误。',
    obtainedFrom: '取得公证档案权限并拿到旧案索引后比对卷宗',
    location: 'notary_hall',
    requiredFlag: 'can_search_notary_archive',
    forbiddenFlags: ['notary_books_burned'],
    setsFlags: ['found_pattern_cases'],
  },

  // ===== X 级：干扰项 =====
  {
    id: 'X1',
    tier: 'X',
    name: '赊账争吵',
    description: '有人说莉娜曾和乔安大吵一架，怀疑她心存报复。这类口风会把结构问题重新缩回“私人恩怨”。',
    obtainedFrom: '莉娜在低信任阶段的自我辩解中提到',
    isFalse: true,
  },
  {
    id: 'X2',
    tier: 'X',
    name: '阿哲偷货',
    description: '阿哲被指偷过码头物资。它会把一个被围猎的孩子重新包装成“并不干净的受害者”。',
    obtainedFrom: '码头闲谈',
    isFalse: true,
  },
  {
    id: 'X3',
    tier: 'X',
    name: '假印章商队',
    description: '传闻外来商队带来假印章。它听上去很像阴谋，却会把视线从制度内部自己的吃法上移开。',
    obtainedFrom: '搜查旧仓库散落的货单',
    location: 'old_warehouse',
    isFalse: true,
  },
];
