import { ClueDefinition } from '../../types';

export const clues: ClueDefinition[] = [
  // ===== A 级：事实层 =====
  {
    id: 'A1',
    tier: 'A',
    name: '驿站日志涂改',
    description: '驿站日志在同一行出现两次不同笔迹的时间记号，确认回执处理确实被延后。',
    obtainedFrom: '搜查驿站柜台后的日志簿',
    location: 'relay_station',
    setsFlags: ['confirmed_lina_delay'],
  },
  {
    id: 'A2',
    tier: 'A',
    name: '半日之差',
    description: '乔安病亡时间与抚恤回执送达时间只差半日，延迟直接影响到救命钱到位。',
    obtainedFrom: '查看港务公告栏上的讣告与收文记录',
    location: 'harbor_gate',
  },
  {
    id: 'A3',
    tier: 'A',
    name: '亲签暂存',
    description: '莉娜在回执背面留有亲签和暂存记号，证明回执确实经过她手。',
    obtainedFrom: '搜查驿站暂存格',
    location: 'relay_station',
  },

  // ===== B 级：责任层 =====
  {
    id: 'B1',
    tier: 'B',
    name: '监护权风险',
    description: '在抚恤到账前，阿哲可能被债主申请临时监护，财产会被代管。',
    obtainedFrom: '阿哲信任度 55+ 后透露债主施压细节（需先建立监护链话题）',
    requiredTrust: { npcId: 'azhe', level: 55 },
    setsFlags: ['guardianship_risk_confirmed'],
  },
  {
    id: 'B2',
    tier: 'B',
    name: '晚送两日交易',
    description: '魏德承认有人出钱要求“晚两日再送”，并交代了代投中转人名。',
    obtainedFrom: '魏德信任度 68+ 后给出口供（需先打开私驿线）',
    requiredTrust: { npcId: 'weide', level: 68 },
    setsFlags: ['exposed_proxy_network'],
  },
  {
    id: 'B3',
    tier: 'B',
    name: '程序最低延迟',
    description: '马修提供书吏记录：即使流程合法，最早也会天然延迟一日。',
    obtainedFrom: '马修信任度 52+ 后出示流程记录',
    requiredTrust: { npcId: 'matthew', level: 52 },
  },
  {
    id: 'B4',
    tier: 'B',
    name: '乔安口供片段',
    description: '乔安临终前留下口供：她不怪莉娜，真正逼死她的是催债链条。',
    obtainedFrom: '阿哲信任度 75+ 后交出母亲口供布条',
    requiredTrust: { npcId: 'azhe', level: 75 },
  },

  // ===== C 级：结构层 =====
  {
    id: 'C1',
    tier: 'C',
    name: '同编号双回执',
    description: '旧仓库里出现两份同编号回执，日期不同、印章一致。',
    obtainedFrom: '拿到仓库钥匙线后搜查旧仓库铁箱',
    location: 'old_warehouse',
    requiredFlag: 'lead_warehouse_key',
    setsFlags: ['found_duplicate_receipt'],
  },
  {
    id: 'C2',
    tier: 'C',
    name: '代投暗账',
    description: '公证所账簿中记录着“代投手续费”，与回执延迟时间高度相关。',
    obtainedFrom: '取得公证档案权限并锁定费码入口后搜查档案柜',
    location: 'notary_hall',
    requiredFlag: 'can_search_notary_archive',
    forbiddenFlags: ['notary_books_burned'],
    setsFlags: ['found_notary_ledger'],
  },
  {
    id: 'C3',
    tier: 'C',
    name: '私驿路线图',
    description: '码头私驿绕开官方时钟登记点，专门制造“时间差盲区”。',
    obtainedFrom: '获得私驿路线线头后搜查码头账房地板夹层',
    location: 'wharf_office',
    requiredFlag: 'lead_private_route',
    setsFlags: ['found_private_route'],
  },
  {
    id: 'C4',
    tier: 'C',
    name: '七起旧案',
    description: '旧档案显示近三年有 7 起“回执晚到后债务重组”案例，模式一致。',
    obtainedFrom: '取得公证档案权限并拿到旧案索引后比对卷宗',
    location: 'notary_hall',
    requiredFlag: 'can_search_notary_archive',
    forbiddenFlags: ['notary_books_burned'],
    setsFlags: ['found_pattern_cases'],
  },

  // ===== X 级：干扰项 =====
  {
    id: 'X1',
    tier: 'X',
    name: '赊账争吵',
    description: '有人说莉娜曾和乔安大吵一架，怀疑她心存报复。（实为赊账冲突）',
    obtainedFrom: '莉娜在低信任阶段的自我辩解中提到',
    isFalse: true,
  },
  {
    id: 'X2',
    tier: 'X',
    name: '阿哲偷货',
    description: '阿哲被指偷过码头物资。（与回执延迟案核心无关）',
    obtainedFrom: '码头闲谈',
    isFalse: true,
  },
  {
    id: 'X3',
    tier: 'X',
    name: '假印章商队',
    description: '传闻外来商队带来假印章。（部分真实，但非本案主因）',
    obtainedFrom: '搜查旧仓库散落的货单',
    location: 'old_warehouse',
    isFalse: true,
  },
];
